SKILLS_DICTIONARY = {
    # Programming Languages
    "python": "python",
    "py": "python",
    "java": "java",
    "javascript": "javascript",
    "js": "javascript",
    "typescript": "typescript",
    "ts": "typescript",
    "c++": "c++",
    "cpp": "c++",
    "c": "c",
    "c#": "c#",
    "c-sharp": "c#",
    "ruby": "ruby",
    "go": "go",
    "golang": "go",
    "php": "php",
    "kotlin": "kotlin",
    "swift": "swift",
    "r": "r",
    "matlab": "matlab",
    "scala": "scala",
    "perl": "perl",

    # Databases
    "mysql": "mysql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "sqlite": "sqlite",
    "mongodb": "mongodb",
    "redis": "redis",
    "cassandra": "cassandra",
    "dynamodb": "dynamodb",
    "oracle": "oracle",
    "mariadb": "mariadb",
    "snowflake": "snowflake",

    # Web Development
    "html": "html",
    "css": "css",
    "bootstrap": "bootstrap",
    "tailwind": "tailwind",
    "tailwind css": "tailwind",
    "sass": "sass",
    "less": "less",

    # Frameworks / Libraries
    "react": "react",
    "reactjs": "react",
    "react.js": "react",
    "nextjs": "nextjs",
    "next.js": "nextjs",
    "angular": "angular",
    "angularjs": "angular",
    "vue": "vue",
    "vue.js": "vue",
    "express": "express",
    "express.js": "express",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "spring": "spring",
    "spring boot": "spring boot",
    "node": "nodejs",
    "node.js": "nodejs",
    "nodejs": "nodejs",

    # Machine Learning / AI
    "ml": "machine learning",
    "machine learning": "machine learning",
    "deep learning": "deep learning",
    "dl": "deep learning",
    "ai": "artificial intelligence",
    "artificial intelligence": "artificial intelligence",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
    "keras": "keras",
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "huggingface": "huggingface",
    "transformers": "huggingface",
    "langchain": "langchain",
    "rag": "retrieval-augmented generation",

    # Cloud & DevOps
    "aws": "aws",
    "aws certified solutions architect": "aws",
    "aws cert": "aws",
    "azure": "azure",
    "gcp": "gcp",
    "google cloud": "gcp",
    "heroku": "heroku",
    "netlify": "netlify",
    "vercel": "vercel",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "jenkins": "jenkins",
    "github actions": "github actions",
    "gitlab ci": "gitlab ci",
    "ci/cd": "cicd",
    "terraform": "terraform",
    "ansible": "ansible",
    "prometheus": "prometheus",
    "grafana": "grafana",

    # Data / Big Data
    "hadoop": "hadoop",
    "spark": "spark",
    "apache spark": "spark",
    "hive": "hive",
    "kafka": "kafka",
    "airflow": "airflow",
    "etl": "etl",
    "data engineering": "data engineering",
    "data science": "data science",
    "pandas": "pandas",
    "numpy": "numpy",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "power bi": "power bi",
    "tableau": "tableau",

    # Tools / Others
    "git": "git",
    "github": "git",
    "gitlab": "git",
    "bitbucket": "git",
    "jira": "jira",
    "confluence": "confluence",
    "vs code": "vs code",
    "visual studio code": "vs code",
    "intellij": "intellij",
    "eclipse": "eclipse",
    "postman": "postman",
    "swagger": "swagger",
    "rest": "rest api",
    "rest api": "rest api",
    "graphql": "graphql"
}


def normalize_skill(skill):
    skill=skill.strip().lower()
    return SKILLS_DICTIONARY.get(skill, skill)